### PR TITLE
Add relative sizes

### PR DESCRIPTION
**Pull request by carl5004**
Adds relative sizes to the flowers and bees json files.

### CODE REVIEW

**Comment by carl5004** [comment]
> Maybe we should have some reasonable min and max values for the scale. We should definitely check that it's greater than 0 at least.

Would those min & max values be written out somewhere in the files? As a required sort of pattern? I think it would be okay without those - they're fairly self-explanatory.

**Comment by floogulinc** [comment]
Numbers in a JSON schema can have a `minimum` and `maximum`. See http://json-schema.org/understanding-json-schema/reference/numeric.html#range

**Comment by carl5004** [comment]
Ok, so what should the min and max be?

**Comment by floogulinc** [comment]
I believe at the meeting on Monday we decided the min would be 0 and the max would be 10 for now.

**Pull request merged**
